### ISSUE TITLE
Delayed generic function error

### ISSUE THREAD

**Issue by tsitsimis** [TileDB-Inc/TileDB-Cloud-Py#217]
Hi!

Following this [guide](https://docs.tiledb.com/cloud/api-reference/task-graphs) I'm running the following:
```python
x = Delayed(np.median)
result_x = x([1,2,3,4,5]).compute()
result_x
```

which runs as expected.

But when running:
```python
def my_median(array):
    return np.median(array)

y = Delayed(my_median)
result_y = y([1,2,3,4,5]).compute()
result_y
```

I get the error:

```
TileDBCloudError: Docker logs: Traceback (most recent call last):
  File "/opt/generic_udf_entry.py", line 599, in <module>
    run_main()
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/conda/lib/python3.7/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/opt/generic_udf_entry.py", line 412, in run_main
    main(**kwargs)
  File "/opt/generic_udf_entry.py", line 449, in main
    udf_function = cloudpickle.loads(pickled_udf)
TypeError: code() takes at most 15 arguments (16 given)

Error(s): received an error from the container: docker container exited with non-zero code: 1. - Code: 5000 - Request ID: 575807e4-7f41-446e-99d9-41e28257c0b5
```

System details:
* tiledb==0.10.4
* tiledb-cloud==0.7.12
* Windows 10

What am I missing?

Thanks for the help!

**Comment by Shelnutt2** [comment]
@tsitsimis this error often occurs when there is a miss-match between python versions. Currently the UDFs require python 3.7 or 3.6. We are expecting to roll out support for 3.8, 3.9, and 3.10 in January 2022.
