### ISSUE TITLE
Error importing on Python 3.5

### ISSUE THREAD

**Issue by ihnorton** [TileDB-Inc/TileDB-Cloud-Py#42]
While checking fix for https://github.com/TileDB-Inc/TileDB-Py/issues/241, I saw the following:
```
ihnorton@DESKTOP-2S2KI39:~$ python3
Python 3.5.2 (default, Oct  8 2019, 13:06:37)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tiledb.cloud
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ihnorton/.local/lib/python3.5/site-packages/tiledb/cloud/__init__.py", line 3, in <module>
    from .client import (
  File "/home/ihnorton/.local/lib/python3.5/site-packages/tiledb/cloud/client.py", line 5, in <module>
    from . import config
  File "/home/ihnorton/.local/lib/python3.5/site-packages/tiledb/cloud/config.py", line 64, in <module>
    logged_in = load_configuration(default_config_file)
  File "/home/ihnorton/.local/lib/python3.5/site-packages/tiledb/cloud/config.py", line 32, in load_configuration
    if not os.path.isfile(config_path):
  File "/usr/lib/python3.5/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: argument should be string, bytes or integer, not PosixPath
>>>
```

Not sure what version of Python we want to support as a minimum, but noting that the default in Ubuntu 16.04 is Python 3.5.

**Comment by Shelnutt2** [comment]
We have CI setup for 3.5, 3.6 and 3.7, so we do want to support 3.5.

**Comment by ihnorton** [comment]
Ok. Noting that this was on WSL1 under Windows 10 with Ubuntu 16.04.

**Comment by jschendel** [comment]
Issue is that `os` wasn't made fully compatible with `pathlib` until 3.6, e.g. see the _Changed in version 3.6_ comment for [`os.path.isfile`](https://docs.python.org/3/library/os.path.html#os.path.isfile).  For compatibility with 3.5 you'll need to explicitly coerce `pathlib.Path` objects to string.

Failing example and workaround for 3.5:
```python
In [1]: import os; import pathlib; import sys

In [2]: sys.version_info   
Out[2]: sys.version_info(major=3, minor=5, micro=6, releaselevel='final', serial=0)

In [3]: foo_path = pathlib.Path('foo.txt')

In [4]: os.path.isfile(foo_path)
---------------------------------------------------------------------------
TypeError: argument should be string, bytes or integer, not PosixPath

In [5]: os.path.isfile(str(foo_path))
Out[5]: False
```

Both the failing example and workaround are fine in 3.6+:
```python
In [1]: import os; import pathlib; import sys

In [2]: sys.version_info
Out[2]: sys.version_info(major=3, minor=6, micro=9, releaselevel='final', serial=0)

In [3]: foo_path = pathlib.Path('foo.txt')

In [4]: os.path.isfile(foo_path)
Out[4]: False

In [5]: os.path.isfile(str(foo_path))
Out[5]: False
```

**Comment by ihnorton** [comment]
Thanks for the pointer, @jschendel!
